# Maternal Health Risk Prediction

## Data Loading & Dataset Overview

### Project Overview

This notebook performs the initial data loading and dataset inspection for the Maternal Health Risk Prediction project.

### Objectives

- Load dataset
- Verify dataset integrity
- Understand dimensions
- Explore column information
- Review sample records
- Generate basic dataset summary

#### Import Required Libraries

In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

#### Load Dataset

In [2]:
data = pd.read_csv("../Dataset/Maternal Health Risk Data Set.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

#### Dataset Shape

In [3]:
print(f"Rows    : {data.shape[0]}")
print(f"Columns : {data.shape[1]}")

Rows    : 1014
Columns : 7

#### Dataset Information

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          1014 non-null   int64
 1   SystolicBP   1014 non-null   int64
 2   DiastolicBP  1014 non-null   int64
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64
 6   RiskLevel    1014 non-null   object
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB

#### Column Names

In [5]:
data.columns.tolist()

['Age',
 'SystolicBP',
 'DiastolicBP',
 'BS',
 'BodyTemp',
 'HeartRate',
 'RiskLevel']

#### First Five Records

In [6]:
data.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

#### Last Five Records

In [7]:
data.tail()

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

#### Random Sample Records

In [8]:
data.sample(10)

     Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
356   35         120           80   6.9      98.0         80  high risk
137   55         140           95  19.0      98.0         77  high risk
813   29         130           70   7.5      98.0         78   mid risk
527   19         120           80   7.0      98.0         70   low risk
237   17          90           60  11.0     101.0         78  high risk
82    12          95           60   6.9      98.0         65   mid risk
412   55         120           90   6.8      98.0         78   low risk
973   17          85           60   9.0     102.0         86  high risk
125   35         140          100   7.5      98.0         66  high risk
221   17          85           60   9.0     102.0         86   mid risk

#### Statistical Summary

In [9]:
data.describe().T

              count        mean        std   min    25%    50%    75%    max
Age          1014.0   29.871795  13.474386  10.0   19.0   26.0   39.0   70.0
SystolicBP   1014.0  113.198225  18.403913  70.0  100.0  120.0  120.0  160.0
DiastolicBP  1014.0   76.460552  13.885796  49.0   65.0   80.0   90.0  100.0
BS           1014.0    8.725986   3.293532   6.0    6.9    7.5    8.0   19.0
BodyTemp     1014.0   98.665089   1.371384  98.0   98.0   98.0   98.0  103.0
HeartRate    1014.0   74.301775   8.088702   7.0   70.0   76.0   80.0   90.0

#### Dataset Memory Usage

In [10]:
memory_usage = data.memory_usage(deep=True).sum() / 1024**2

print(f"Memory Usage : {memory_usage:.2f} MB")

Memory Usage : 0.11 MB

#### Target Variable Overview

In [11]:
data["RiskLevel"].value_counts()

RiskLevel
low risk     406
mid risk     336
high risk    272
Name: count, dtype: int64

#### Save Raw Dataset Copy

In [12]:
data.to_csv("../Dataset/raw_dataset.csv", index=False)

print("Raw Dataset Saved Successfully")

Raw Dataset Saved Successfully